# Generated by Django 4.2.7 on 2025-07-23 09:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('marcas_registradas_mes_actual', models.IntegerField(default=0)),
                ('tiempo_promedio_procesamiento', models.FloatField(default=0)),
                ('porcentaje_aprobacion', models.FloatField(default=0)),
                ('porcentaje_rechazo', models.FloatField(default=0)),
                ('ingresos_mes_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cabezas_bovinas', models.IntegerField(default=0)),
                ('promedio_cabezas_por_marca', models.FloatField(default=0)),
                ('porcentaje_carne', models.FloatField(default=0)),
                ('porcentaje_leche', models.FloatField(default=0)),
                ('porcentaje_doble_proposito', models.FloatField(default=0)),
                ('porcentaje_reproduccion', models.FloatField(default=0)),
                ('raza_mas_comun', models.CharField(default='', max_length=100)),
                ('porcentaje_raza_principal', models.FloatField(default=0)),
                ('tasa_exito_logos', models.FloatField(default=0)),
                ('total_marcas_sistema', models.IntegerField(default=0)),
                ('marcas_pendientes', models.IntegerField(default=0)),
                ('alertas', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Datos del Dashboard',
                'verbose_name_plural': 'Datos del Dashboard',
                'db_table': 'dashboard_data',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='ReporteDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_reporte', models.CharField(max_length=50)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('formato', models.CharField(default='json', max_length=20)),
                ('datos', models.JSONField()),
                ('usuario_generador', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Datos de Reporte',
                'verbose_name_plural': 'Datos de Reportes',
                'db_table': 'reporte_data',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='MarcaGanadoBovinoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_marca', models.CharField(help_text='Número único de identificación de la marca', max_length=50, unique=True)),
                ('nombre_productor', models.CharField(help_text='Nombre completo del productor ganadero', max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro de la solicitud')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, help_text='Fecha y hora cuando se procesó la certificación', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('EN_PROCESO', 'EN_PROCESO'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], default='PENDIENTE', help_text='Estado actual del proceso de certificación', max_length=20)),
                ('monto_certificacion', models.DecimalField(decimal_places=2, default=0, help_text='Costo de la certificación en bolivianos', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('raza_bovino', models.CharField(choices=[('CRIOLLO', 'CRIOLLO'), ('NELORE', 'NELORE'), ('BRAHMAN', 'BRAHMAN'), ('SANTA_GERTRUDIS', 'SANTA_GERTRUDIS'), ('CHAROLAIS', 'CHAROLAIS'), ('HOLSTEIN', 'HOLSTEIN'), ('SIMMENTAL', 'SIMMENTAL'), ('ANGUS', 'ANGUS'), ('HEREFORD', 'HEREFORD'), ('GUZERAT', 'GUZERAT'), ('MIXTO', 'MIXTO'), ('OTRO', 'OTRO')], default='CRIOLLO', help_text='Raza del ganado bovino', max_length=100)),
                ('proposito_ganado', models.CharField(choices=[('CARNE', 'CARNE'), ('LECHE', 'LECHE'), ('DOBLE_PROPOSITO', 'DOBLE_PROPOSITO'), ('REPRODUCCION', 'REPRODUCCION')], default='CARNE', help_text='Propósito principal del ganado', max_length=50)),
                ('cantidad_cabezas', models.IntegerField(help_text='Número de cabezas de ganado bovino registradas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('departamento', models.CharField(choices=[('LA_PAZ', 'LA_PAZ'), ('SANTA_CRUZ', 'SANTA_CRUZ'), ('COCHABAMBA', 'COCHABAMBA'), ('POTOSI', 'POTOSI'), ('ORURO', 'ORURO'), ('CHUQUISACA', 'CHUQUISACA'), ('TARIJA', 'TARIJA'), ('BENI', 'BENI'), ('PANDO', 'PANDO')], help_text='Departamento donde se encuentra el ganado', max_length=100)),
                ('municipio', models.CharField(help_text='Municipio donde se encuentra el ganado', max_length=100)),
                ('comunidad', models.CharField(blank=True, help_text='Comunidad o zona específica (opcional)', max_length=150, null=True)),
                ('ci_productor', models.CharField(help_text='Cédula de identidad del productor', max_length=20)),
                ('telefono_productor', models.CharField(blank=True, help_text='Teléfono de contacto del productor', max_length=20, null=True)),
                ('tiempo_procesamiento_horas', models.IntegerField(blank=True, help_text='Tiempo total de procesamiento en horas', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la marca o el proceso', null=True)),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que registró la marca', max_length=100, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marca de Ganado Bovino',
                'verbose_name_plural': 'Marcas de Ganado Bovino',
                'db_table': 'marca_ganado_bovino',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['numero_marca'], name='marca_ganad_numero__d8ce01_idx'), models.Index(fields=['estado'], name='marca_ganad_estado_35f745_idx'), models.Index(fields=['departamento'], name='marca_ganad_departa_795312_idx'), models.Index(fields=['fecha_registro'], name='marca_ganad_fecha_r_478a80_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogoMarcaBovinaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_logo', models.URLField(help_text='URL donde se almacena el logo generado')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('exito', models.BooleanField(default=True, help_text='Indica si la generación fue exitosa')),
                ('tiempo_generacion_segundos', models.IntegerField(help_text='Tiempo que tomó generar el logo en segundos', validators=[django.core.validators.MinValueValidator(0)])),
                ('modelo_ia_usado', models.CharField(choices=[('GPT-4', 'GPT-4'), ('DALL-E-3', 'DALL-E-3'), ('DALL-E-2', 'DALL-E-2'), ('MIDJOURNEY', 'MIDJOURNEY'), ('STABLE_DIFFUSION', 'STABLE_DIFFUSION'), ('LEONARDO_AI', 'LEONARDO_AI')], help_text='Modelo de IA utilizado para generar el logo', max_length=100)),
                ('prompt_usado', models.TextField(blank=True, help_text='Prompt utilizado para generar el logo', null=True)),
                ('calidad_logo', models.CharField(choices=[('ALTA', 'ALTA'), ('MEDIA', 'MEDIA'), ('BAJA', 'BAJA')], default='MEDIA', help_text='Calidad percibida del logo generado', max_length=20)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='analytics.marcaganadobovinomodel')),
            ],
            options={
                'verbose_name': 'Logo de Marca Bovina',
                'verbose_name_plural': 'Logos de Marcas Bovinas',
                'db_table': 'logo_marca_bovina',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='KPIGanadoBovinoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('marcas_registradas_mes', models.IntegerField(default=0, help_text='Número de marcas bovinas registradas en el mes')),
                ('tiempo_promedio_procesamiento', models.FloatField(default=0, help_text='Tiempo promedio de procesamiento en horas')),
                ('porcentaje_aprobacion', models.FloatField(default=0, help_text='Porcentaje de marcas aprobadas')),
                ('ingresos_mes', models.DecimalField(decimal_places=2, default=0, help_text='Ingresos generados en el mes', max_digits=15)),
                ('total_cabezas_registradas', models.IntegerField(default=0, help_text='Total de cabezas de ganado bovino registradas')),
                ('promedio_cabezas_por_marca', models.FloatField(default=0, help_text='Promedio de cabezas por marca registrada')),
                ('marcas_carne', models.IntegerField(default=0)),
                ('marcas_leche', models.IntegerField(default=0)),
                ('marcas_doble_proposito', models.IntegerField(default=0)),
                ('marcas_reproduccion', models.IntegerField(default=0)),
                ('marcas_santa_cruz', models.IntegerField(default=0)),
                ('marcas_beni', models.IntegerField(default=0)),
                ('marcas_la_paz', models.IntegerField(default=0)),
                ('marcas_otros_departamentos', models.IntegerField(default=0)),
                ('tasa_exito_logos', models.FloatField(default=0, help_text='Porcentaje de logos generados exitosamente')),
                ('total_logos_generados', models.IntegerField(default=0, help_text='Total de logos generados en el mes')),
                ('tiempo_promedio_generacion_logos', models.FloatField(default=0, help_text='Tiempo promedio de generación de logos en segundos')),
            ],
            options={
                'verbose_name': 'KPI Ganado Bovino',
                'verbose_name_plural': 'KPIs Ganado Bovino',
                'db_table': 'kpi_ganado_bovino',
                'ordering': ['-fecha'],
                'unique_together': {('fecha',)},
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoMarcaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('usuario_responsable', models.CharField(blank=True, help_text='Usuario que realizó el cambio de estado', max_length=100, null=True)),
                ('observaciones_cambio', models.TextField(blank=True, help_text='Observaciones sobre el cambio de estado', null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='analytics.marcaganadobovinomodel')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historiales de Estados',
                'db_table': 'historial_estado_marca',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
