# Generated by Django 4.2.23 on 2025-07-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kpiganadobovinomodel",
            name="fecha",
            field=models.DateField(),
        ),
    ]
